/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Author: Basma Walid
 *
 * Date Created : Oct 12,2022
 *
 * Description: Source file for the Ultrasonic driver
 *
 *******************************************************************************/

#include "ultrasonic.h" /* Header file of the Module*/
#include "icu.h" /* For Initializing the ICU Init and set up call back*/
#include "gpio.h" /* For setting pins as inputs and outputs*/
#include<util/delay.h> /* For Pulse Creation*/
#include "std_types.h" /* For output high and low logics on pins */

/* count --> Used for counting the edges */
static uint8 count =0;

/* time_taken --> Time taken by the echo pin to receive the wave*/
static uint16 time_taken =0;


/* Description :
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void ULTRASONIC_init(void)
{
	/*
	 * ICU Setup
	 * F_CPU_8 --> Work with internal frequency 8 Mhz
	 * RISING --> Work with Rising edge
	 */
	Icu_ConfigType config={F_CPU_8,RISING};

	/* Passing the configuration structure by address to the ICU_Init function */
	Icu_init(&config);

	/* Setting up the call back function*/
	Icu_setCallBack(ULTRASONIC_edgeProcessing);

	/* Setting up PB5 to be an output pin -->Trigger pin*/
	GPIO_setupPinDirection(PORTB_ID ,PIN5_ID ,PIN_OUTPUT);
	GPIO_writePin(PORTB_ID , PIN5_ID ,LOGIC_LOW);
}


 /*Description :
 * Send the Trigger pulse to the ultrasonic .
 */
void ULTRASONIC_Trigger(void)
{
	/* Pulse of width 1o us */
	GPIO_writePin(PORTB_ID , PIN5_ID ,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID , PIN5_ID ,LOGIC_LOW);
}


/*Description
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 ULTRASONIC_readDistance(void)
{
	uint16 distance =0;

	/* Triggering the ultrasonic*/
	ULTRASONIC_Trigger();


	/* Calculating the distance */
	distance=time_taken/57.5;
	return distance ;
}

/*
 * Description :
 * This is the call back function called by the ICU driver.
 *
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 */
void ULTRASONIC_edgeProcessing(void)
{
	/* Increment the count */
	count++;
	if(count == 1 )
	{
		/* Clear the Timer Value*/
		Icu_clearTimerValue();

		/* Work with falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(count == 2)
	{
		/* Time Taken by the wave to go and return back*/
		time_taken=Icu_getInputCaptureValue();

		/* Work with rising edge */
		Icu_setEdgeDetectionType(RISING);

		/* Reset the counter to prepare for the next capture*/
		count=0;
	}
}


